"""The Copilot's OWN tables (drafts + audit) in schema "copilot", plus read-only access to MediTrack.

Login "copilot_svc" (search_path = copilot, mis):
  - owns schema copilot           -> draft, event
  - member of IT's mis_ro role     -> SELECT on the mis reporting views of MediTrack's tables, nothing else
"""
import os
from datetime import datetime
from pathlib import Path

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from copilot_core.encounter import upper_row

DB_URL = os.getenv("COPILOT_DB_URL", "postgresql://copilot_svc:copilot_svc@localhost:5432/citycare")
DATA = Path(os.getenv("COPILOT_DATA_DIR", Path(__file__).resolve().parent.parent / "data"))   # print previews only

SCHEMA = """
CREATE TABLE IF NOT EXISTS copilot.draft (
    ip_no TEXT PRIMARY KEY, status TEXT, advised_at TEXT, ready_at TEXT, signed_at TEXT, signed_by TEXT,
    source TEXT, model TEXT, latency_ms INT, input_tokens INT, output_tokens INT, cost_usd DOUBLE PRECISION,
    draft_json TEXT, edited_json TEXT, edit_pct DOUBLE PRECISION, tpa_score_at_sign INT, trace_flags INT, pdf_file TEXT, error TEXT
);
CREATE TABLE IF NOT EXISTS copilot.event (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT, ip_no TEXT, actor TEXT, action TEXT, detail TEXT
);
"""

_pool: ConnectionPool | None = None


def now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        _pool = ConnectionPool(DB_URL, min_size=1, max_size=6, open=True)
    return _pool


def init() -> None:
    with psycopg.connect(DB_URL) as c:
        c.execute(SCHEMA)


def reset() -> None:
    """Clear all drafts and events (demo reset)."""
    with psycopg.connect(DB_URL) as c:
        c.execute("DROP TABLE IF EXISTS copilot.draft, copilot.event")
        c.execute(SCHEMA)


class _Conn:
    """`with db() as c:` / `with mis() as r:` -> pooled connection with the right row shape; commits on success."""

    def __init__(self, row_factory):
        self.row_factory = row_factory

    def __enter__(self) -> psycopg.Connection:
        self._cm = _get_pool().connection()
        c = self._cm.__enter__()
        c.row_factory = self.row_factory
        return c

    def __exit__(self, *exc):
        return self._cm.__exit__(*exc)


def db() -> _Conn:
    """The Copilot's own tables: dict rows with lowercase keys."""
    return _Conn(dict_row)


def mis() -> _Conn:
    """MediTrack data through IT's read-only mis views: dict rows with MediTrack's UPPERCASE keys."""
    return _Conn(upper_row)


def event(ip_no: str, actor: str, action: str, detail: str = "") -> None:
    with db() as c:
        c.execute("INSERT INTO event (ts, ip_no, actor, action, detail) VALUES (%s,%s,%s,%s,%s)",
                  (now(), ip_no, actor, action, detail))
